version: '3.9'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.41.0
    container_name: jaeger
    environment:
      COLLECTOR_OTLP_HTTP_CORS_ALLOWED_ORIGINS: "http://localhost:4318/"
      COLLECTOR_OTLP_HTTP_CORS_ALLOWED_HEADERS: "*"
      COLLECTOR_OTLP_ENABLED: "true"
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "4317:4317"
      - "9411:9411"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "4318:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - jaeger
