---
- name: Setup Topology Bootstrap
  hosts: topology_bootstrap
  vars:
    mode: "bootstrap"
    docker_port: "6960"
  roles:
    - "../roles/common"
    - "../roles/topology-node"

#- name: Setup Topology Node
#  hosts: topology_node
#  vars:
#    mode: "node"
#    docker_port: '69{{ inventory_hostname | regex_replace(".*\D(\d+).*", "\1") }}'
#  roles:
#    - "../roles/common"
#    - "../roles/topology-node"

- name: Setup proxy
  hosts: topology_bootstrap
  vars:
    sites:
      "{{ inventory_hostname }}=http://172.17.0.1:50000"
      # ;{{ groups["topology_node"]
      #   | map("regex_replace", "(.*\D)(\d+)(.*)", "\1\2\3=http://172.17.0.1:69\2")
      #   | list
      #   | join(";")
      # }}"
  roles:
    - "../roles/proxy"

- name: Setup Prometheus
  hosts: prometheus.topology.gg
  vars:
    prometheus_port: "9090"
    pushgateway_host: "pushgateway.topology.gg"
    pushgateway_port: "9091"
    services_to_deploy: ["prometheus", "metrics-cleanup"]
  roles:
    - "../roles/common"
    - "../roles/prometheus-grafana"

- name: Setup Pushgateway
  hosts: pushgateway.topology.gg
  vars:
    pushgateway_port: "9091"
    services_to_deploy: ["pushgateway"]
  roles:
    - "../roles/common"
    - "../roles/prometheus-grafana"

- name: Setup Grafana
  hosts: grafana.topology.gg
  vars:
    grafana_port: "3000"
    grafana_admin_password: "admin" # Change this in production
    prometheus_server: "prometheus.topology.gg"
    services_to_deploy: ["grafana"]
  roles:
    - "../roles/common"
    - "../roles/prometheus-grafana"
